# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# https://help.github.com/articles/removing-relative-permalinks
#relative_permalinks: true

# Setup
title:               "Galaxy's World"
tagline:             '银河雪尘'
description:         'My Blog. Written by <a href="https://twitter.com/galaxy001" target="_blank">@galaxy001</a>.'
url:                 https://galaxysd.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Yuuki Galaxy'
  url:               https://twitter.com/galaxy001
  email:             galaxy001(at)gmail.com

# Custom vars
version:             1.0.0
